# GitHub Action to build Go
# jtruk / RiFT
# First version: 2023-09-11

name: Build Releases

# Trigger workflow when we push to main, or manually start it
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
    # Check-out this repository under $GITHUB_WORKSPACE
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: './go.mod'

    - name: Build Linux
      run: GOOS=linux GOARCH=amd64 go build -o ./release/tic-80-bundler-linux-64.exe

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -o ./release/tic-80-bundler-win-64.exe

    - name: Build Mac
      run: GOOS=darwin GOARCH=amd64 go build -o ./release/tic-80-bundler-mac-64.exe

    - name: Upload Linux
      uses: actions/upload-artifact@v3
      with:
        name: tic-80-bundler-linux
        path: |
          ./README.md
          ./release/tic-80-bundler-linux-64.exe

    - name: Upload Windows
      uses: actions/upload-artifact@v3
      with:
        name: tic-80-bundler-windows
        path: |
          ./README.md
          ./release/tic-80-bundler-win-64.exe

    - name: Upload Mac
      uses: actions/upload-artifact@v3
      with:
        name: tic-80-bundler-mac
        path: |
          ./README.md
          ./release/tic-80-bundler-mac-64.exe